"use client";

// components/documentation/DocumentationHistoryView.tsx
// Page 2 — Documentation History. A searchable log of every generated note,
// independent of which Open Loop (if any) it's linked to.

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/Button";
import { Toast, type ToastMessage } from "@/components/ui/Toast";
import { OpenLoopEmptyState } from "@/components/open-loops/OpenLoopEmptyState";
import { DocumentationHistoryFilterBar } from "@/components/documentation/DocumentationHistoryFilterBar";
import { DocumentationHistoryList } from "@/components/documentation/DocumentationHistoryList";
import { DocumentationEntryModal } from "@/components/documentation/DocumentationEntryModal";
import { useDocumentationHistory } from "@/hooks/use-documentation-history";
import { getOpenLoops } from "@/services/open-loops.service";
import type { DocumentationEntry, OpenLoop } from "@/types";

export function DocumentationHistoryView() {
  const { entries, isLoading, filters, setFilters } = useDocumentationHistory();
  const [openLoops, setOpenLoops] = useState<OpenLoop[]>([]);
  const [selectedEntry, setSelectedEntry] = useState<DocumentationEntry | null>(null);
  const [toast, setToast] = useState<ToastMessage | null>(null);

  useEffect(() => {
    let isMounted = true;
    void getOpenLoops().then((loops) => {
      if (isMounted) setOpenLoops(loops);
    });
    return () => {
      isMounted = false;
    };
  }, []);

  const openLoopsById = useMemo(() => new Map(openLoops.map((loop) => [loop.id, loop])), [openLoops]);

  const handleCopy = useCallback(async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setToast({ id: Date.now(), text: "Copied to clipboard.", tone: "success" });
    } catch {
      setToast({ id: Date.now(), text: "Couldn't copy — select and copy manually.", tone: "error" });
    }
  }, []);

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Documentation History"
        description="Every note generated by the Clinical Documentation module, searchable by patient, date, template, or category."
        action={
          <Link href="/clinical-documentation">
            <Button variant="secondary">
              <ArrowLeft className="h-4 w-4" aria-hidden="true" />
              Back to Clinical Documentation
            </Button>
          </Link>
        }
      />

      <DocumentationHistoryFilterBar filters={filters} onChange={setFilters} />

      {isLoading ? (
        <p className="text-sm text-accent/50">Loading documentation history…</p>
      ) : entries.length === 0 ? (
        <OpenLoopEmptyState message="No documentation entries match these filters." />
      ) : (
        <DocumentationHistoryList
          entries={entries}
          openLoopsById={openLoopsById}
          onSelectEntry={setSelectedEntry}
        />
      )}

      <DocumentationEntryModal
        entry={selectedEntry}
        relatedLoop={selectedEntry?.relatedOpenLoopId ? openLoopsById.get(selectedEntry.relatedOpenLoopId) ?? null : null}
        onClose={() => setSelectedEntry(null)}
        onCopy={handleCopy}
      />

      <Toast toast={toast} onDismiss={() => setToast(null)} />
    </div>
  );
}
