// scripts/generate-seed-sql.ts
// One-off generator, not part of the app bundle: reads the existing mock
// data modules (the same ones services/*.service.ts used before Phase 10)
// and prints the equivalent `insert into ...` statements for supabase/seed.sql.
// Run with: node --experimental-strip-types scripts/generate-seed-sql.ts
//
// This exists so seed.sql is generated FROM the mock data verbatim rather
// than hand-retyped (and risking a transcription mistake), per the Phase 10
// brief's "Use the existing mock content."

import { MOCK_PATIENTS } from "../lib/mock/patients.ts";
import { MOCK_PROVIDERS } from "../lib/mock/providers.ts";
import { MOCK_CLINIC_CONTACTS } from "../lib/mock/clinic-contacts.ts";
import { DOCUMENTATION_TEMPLATES } from "../lib/constants/documentation-templates.ts";

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  const escaped = values.map((v) => `"${v.replace(/"/g, '\\"').replace(/'/g, "''")}"`);
  return `'{${escaped.join(",")}}'`;
}

function sqlJson(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [];

lines.push("-- supabase/seed.sql");
lines.push("-- Generated by scripts/generate-seed-sql.ts from the app's own Phase 1-9 mock data");
lines.push("-- (lib/mock/*.ts, lib/constants/documentation-templates.ts) — regenerate this file");
lines.push("-- any time that mock data changes rather than hand-editing it.");
lines.push("--");
lines.push("-- Run against a fresh project (after the migrations in supabase/migrations/ have");
lines.push("-- applied) with the Supabase CLI: `supabase db execute -f supabase/seed.sql`, or");
lines.push("-- paste it into the SQL Editor. It assumes exactly one signed-up user — the HVA —");
lines.push("-- and looks up that user's id (the earliest-created row in auth.users) so every");
lines.push("-- row's `user_id` can be set explicitly, since there is no authenticated request");
lines.push("-- context (and so no auth.uid()) when running a seed script from the SQL Editor");
lines.push("-- or CLI.");
lines.push("--");
lines.push("-- NOTE: Open Loops, Activities, Documentation History, Workflow Runs, and");
lines.push("-- Communication Logs are NOT seeded here. Phase 1-9's mock data for those was");
lines.push("-- written to make the mock in-memory services demonstrate cross-module features");
lines.push("-- (matching patient names across modules, etc.) and is intentionally NOT carried");
lines.push("-- into the real database — a production HVA account should start with a clean");
lines.push("-- slate for its own day-to-day activity. Only genuinely reusable reference/setup");
lines.push("-- data — Patients, Providers, Documentation Templates, and Clinic Contacts (with");
lines.push("-- their Communication Logs) — is seeded.");
lines.push("");
lines.push("do $$");
lines.push("declare");
lines.push("  v_user_id uuid;");
lines.push("begin");
lines.push("  select id into v_user_id from auth.users order by created_at asc limit 1;");
lines.push("  if v_user_id is null then");
lines.push("    raise exception 'No user found in auth.users — sign up the HVA account first, then re-run this seed.';");
lines.push("  end if;");
lines.push("");

// ---- documentation_templates (no user_id — shared reference table) ----
lines.push("  -- documentation_templates: shared reference data, no user_id");
for (const template of DOCUMENTATION_TEMPLATES) {
  lines.push(
    `  insert into public.documentation_templates (id, category, label, fields, help) values (` +
      `${sqlString(template.id)}, ${sqlString(template.category)}, ${sqlString(template.label)}, ` +
      `${sqlJson(template.fields)}, ${sqlJson(template.help)}) on conflict (id) do update set ` +
      `category = excluded.category, label = excluded.label, fields = excluded.fields, help = excluded.help;`,
  );
}
lines.push("");

// ---- providers ----
lines.push("  -- providers");
for (const provider of MOCK_PROVIDERS) {
  lines.push(
    `  insert into public.providers (user_id, name, specialty, clinic_days, notes, related_workflow_ids) values (` +
      `v_user_id, ${sqlString(provider.name)}, ${sqlString(provider.specialty)}, ` +
      `${sqlTextArray(provider.clinicDays)}, ${sqlString(provider.notes)}, ` +
      `${sqlTextArray(provider.relatedWorkflowIds)});`,
  );
}
lines.push("");

// ---- patients ----
lines.push("  -- patients");
for (const patient of MOCK_PATIENTS) {
  lines.push(
    `  insert into public.patients (user_id, name, aliases, dob, provider, program, phone, email) values (` +
      `v_user_id, ${sqlString(patient.name)}, ${sqlTextArray(patient.aliases)}, ${sqlString(patient.dob)}, ` +
      `${sqlString(patient.provider)}, ${sqlString(patient.program)}, ${sqlString(patient.phone)}, ` +
      `${sqlString(patient.email)});`,
  );
}
lines.push("");

// ---- clinic_contacts + communication_logs ----
lines.push("  -- clinic_contacts, each followed by its own communication_logs rows");
for (const contact of MOCK_CLINIC_CONTACTS) {
  lines.push("  declare v_contact_id uuid; begin");
  lines.push(
    `    insert into public.clinic_contacts (user_id, name, category, phone, fax, email, address, notes) values (` +
      `v_user_id, ${sqlString(contact.name)}, ${sqlString(contact.category)}, ${sqlString(contact.phone)}, ` +
      `${sqlString(contact.fax)}, ${sqlString(contact.email)}, ${sqlString(contact.address)}, ` +
      `${sqlString(contact.notes)}) returning id into v_contact_id;`,
  );
  for (const entry of contact.communicationLog) {
    lines.push(
      `    insert into public.communication_logs (user_id, contact_id, date, method, summary, performer) values (` +
        `v_user_id, v_contact_id, ${sqlString(entry.date)}, ${sqlString(entry.method)}, ` +
        `${sqlString(entry.summary)}, ${sqlString(entry.performer)});`,
    );
  }
  lines.push("  end;");
}
lines.push("");
lines.push("end $$;");
lines.push("");

console.log(lines.join("\n"));
